### ISSUE TITLE
Error in running LongQC sampleqc for ONT ligation data

### ISSUE THREAD

**Issue by XueyiDong** [yfukasawa/LongQC#13]
Hi @yfukasawa ,

Thanks for this useful tool kit. I was running LongQC on my ONT direct cDNA sequencing data using the following script.
`python longQC.py sampleqc -x ont-ligation -p 4 -o $out/barcode01 $input/barcode01.fq.gz`

The `analysis/subsample.fastq` file were successfully generated together with minimap coverage error and out txt file. However, the `figs` folder is empty, and I got the following error:
```
lq_gcfrac:2020-07-20 15:02:39,582:58:INFO:Kernel density estimation done for read GC composition
Traceback (most recent call last):
  File "longQC.py", line 932, in <module>
    main(args)
  File "longQC.py", line 62, in main
    args.handler(args)
  File "longQC.py", line 435, in command_sample
    gc_read_mean, gc_read_sd = lg.plot_unmasked_gc_frac(fp=fig_path_gc)
  File "/stornext/Home/data/allstaff/d/dong.x/Programs/LongQC/lq_gcfrac.py", line 60, in plot_unmasked_gc_frac
    plt.hist(self.c_frac, alpha=0.3, bins=np.arange(min(self.c_frac), max(self.c_frac) + b_width, b_width), color='red', density=True)
ValueError: min() arg is an empty sequence
```
Could you please tell me how to fix the problem?

Thanks,
Xueyi

**Comment by yfukasawa** [comment]
Hello @XueyiDong,

Sorry for very late response. If you're still interested in this issue, please see below.

GC fraction is computed by another program 'sdust' in the package, and if this worked fine, you should see a file named **longqc_sdust.txt**. 
I expect this file wasn't generated or collapsed due to some reasons.
From the error messages, I think the program tried to load this file, and it failed.

Yoshinori
