### ISSUE TITLE
LOngQc installtion issue

### ISSUE THREAD

**Issue by drSuryatamil** [yfukasawa/LongQC#30]
cd LongQC-1.2.0c/minimap2-coverage && make
cc -c -g -O2 -Wall -Wc++-compat -DHAVE_KALLOC  minimap2-coverage.c -o minimap2-coverage.o
minimap2-coverage.c:1:10: fatal error: stdlib.h: No such file or directory
    1 | #include <stdlib.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:29: minimap2-coverage.o] Error 1
im facing this issue. kindly help me to sort out this. Thanks

**Comment by yfukasawa** [comment]
Hi @drSuryatamil,

Thank you for having interest in our tool.
The error looks to be caused by your system rather than the code itself.
Which OS did you try to install to? Mac OS or Linux?

Y.

**Comment by drSuryatamil** [comment]
Hi, yfukasawa, we are using linux ubuntu latest version. kindly suggest me easy way to get install the LongQC tool. 
Thanking You,

**Comment by yfukasawa** [comment]
Hi,

Thanks for letting me know. You can try LongQC on Docker, if Docker is available on your computer.
How to use Docker is available on Readme.
If this is not the case, compilation would be needed.

`fatal error: stdlib.h: No such file or directory`
This error should be raised by missing of some files on your computer rather than an issue in LongQC.

As discussed below, you can try this command to install required package: `sudo apt-get install libc6-dev`
Ref: [https://stackoverflow.com/questions/19580758/gcc-fatal-error-stdio-h-no-such-file-or-directory/29284967#29284967](https://stackoverflow.com/questions/19580758/gcc-fatal-error-stdio-h-no-such-file-or-directory/29284967#29284967)

Y.
