### ISSUE TITLE
Blank QV plots?

### ISSUE THREAD

**Issue by bibionid** [yfukasawa/LongQC#40]
Hello, 

Thanks for making this awesome tool! I'm recently installed it and am trying to use the `sampleqc` tool. I am running with the below call: 

`longQC.py sampleqc -p 16 -m 2 -d -x pb-hifi -s <sample_name> -o <out_dir> <sample_name.bam>`

The tools appears to have run without any errors, but some of the output is not as I expected? 

The `fig_longQC_sampleqc_average_qv_<sample_name>.png` and `fig_longQC_sampleqc_olp_qv_<sample_name>.png` files appear as below:

![Screenshot 2021-11-17 at 20 00 08](https://user-images.githubusercontent.com/10674185/142273530-3c6cb6f5-4aad-4a95-92a5-eab04c26f92a.png)

![Screenshot 2021-11-17 at 20 01 09](https://user-images.githubusercontent.com/10674185/142273663-6312f6e1-e428-4c42-9b9d-003c22f6b9ab.png)

Is this expected for a given error, or do I need to review my installation? No error messages were created. 

Many thanks in advance!

**Comment by yfukasawa** [comment]
Hello @bibionid ,

Sorry for heavy delay due to my personal situation, but thank you for asking.
You're absolutely right, and I'm aware of this issue, which happens when HiFi input format is bam.

This can be resolved relatively easily by tweaking codes for pysam, but it gets quite slower. The tentative workaround is using fastq format, and I hope this answer helps you.

Y.

**Comment by bibionid** [comment]
Hi @yfukasawa 

Thank you very much for you time in responding here, this is even more valuable given the strain on your time. 

Thank you fo suggesting the workaround - I have since tried using fastq and did successfully generate the plots. 

Best wishes!
