### ISSUE TITLE
Revio data

### ISSUE THREAD

**Issue by crazysummerW** [yfukasawa/LongQC#60]
hello，
I wonder if this program can be used for Pacbio Revio data?

Looking forward to your reply.
Thanks.

**Comment by yfukasawa** [comment]
Hi @crazysummerW,

Thanks for your interests in our tool!

Yes, LongQC should be able to handle the Revio data. Please use HiFi profile for the data from Revio. Technically speaking, Revio data is a better HiFi data making use of a new AI model than that generated on Sequel II.

If you face some problems, kindly let me know.

Yoshinori

**Comment by crazysummerW** [comment]
hi @yfukasawa ,
Thanks for your reply.
When testing revio hifi_reads.bam, which args should I choose? Are they the same as for sequel data?
just like:
`python longQC.py sampleqc -x pb-sequel -o out_dir revio_hifi_reads.bam`

Looking forward to your reply.
Thanks.

**Comment by yfukasawa** [comment]
Hi, sorry for delayed response.

>python longQC.py sampleqc -x pb-sequel -o out_dir revio_hifi_reads.aligned..bam

if this is hifi data, I recommend to use `-x pb-hifi` instead of -x pb-sequel as pb-sequel is for CLR dataset.

>where can I find detailed instructions for the results files and web_summary.html?

Help message is included in html file, and if you want further details, it's written in our article published in G3. please check supplementary file as I wrote detailed guide. Basic ideas have remained the same.

>How can I obtain the coverage at different depths

Well, question is not very clear to me. in usual, coverage and depth mean the same. Coverage plot of LongQC returns average per-read coverage, intuitively how many times a base was sequenced in your dataset. You can call this metric as depth.

Or you want to know how much fraction of the genome is sequenced?

**Comment by crazysummerW** [comment]
@yfukasawa 
Thanks for your reply.
Regarding the third question, what I mean is, can I obtain the statistics similar to gatk [CollectWgsMetrics](https://broadinstitute.github.io/picard/picard-metric-definitions.html#CollectWgsMetrics.WgsMetrics)?
Such as, PCT_5X, PCT_10X, PCT_20X, PCT_30X...

And, I have one more question.
Can LongQC provide alignment rate and uniformity? Perhaps you have other statistical software recommendations for PacBio data?

Looking forward to your reply.
Thanks.

**Comment by yfukasawa** [comment]
>Regarding the third question, what I mean is, can I obtain the statistics similar to gatk CollectWgsMetrics?

Ah, ok, got it, thanks!
Short answer is unfortunately no. This type of metric requires a reference sequence and mapping to the reference, and LongQC tries to evaluate the dataset without any reference. So, I would say that concept is similar but distinct.
You can get estimated mean coverage for your dataset by LongQC.

Re. QV, it should be blank as you found for your bam input. Kindly check #40 as well.
we have not accepted n-fold slower performance to generate QV plot for the bam input.

Hope this clarifies your question.

Y.
